last_change = 2026-09-09T16:19:01.064148Z
addr = 0xa2f570
size = 0x1
name = "IGameSystem_OnServerPreClientUpdate"

[header]
name = "IGameSystem_OnServerPreClientUpdate"
addr = 0xa2f570

[header.args]
