last_change = 2026-09-09T16:19:01.064156Z
addr = 0xa2f5c0
size = 0x1
name = "IGameSystem_OnServerPostAdvanceTick"

[header]
name = "IGameSystem_OnServerPostAdvanceTick"
addr = 0xa2f5c0

[header.args]
