last_change = 2026-09-09T16:19:01.064107Z
addr = 0xa2f3c0
size = 0x1
name = "IGameSystem_OnBuildGameSessionManifest"

[header]
name = "IGameSystem_OnBuildGameSessionManifest"
addr = 0xa2f3c0

[header.args]
