last_change = 2026-09-09T16:19:01.064420Z
addr = 0xf4b2b0
size = 0x14a
name = "CSpawnGroupMgrGameSystem_GetSpawnGroups"

[header]
name = "CSpawnGroupMgrGameSystem_GetSpawnGroups"
addr = 0xf4b2b0

[header.args]
