last_change = 2026-09-09T16:19:01.064428Z
addr = 0xf56970
size = 0x410
name = "CSpawnGroupMgrGameSystem_SpawnGroupSpawnEntities"

[header]
name = "CSpawnGroupMgrGameSystem_SpawnGroupSpawnEntities"
addr = 0xf56970

[header.args]
