last_change = 2026-09-09T16:19:01.064430Z
addr = 0xf6ee60
size = 0x311
name = "CSpawnGroupMgrGameSystem_UnloadSpawnGroup"

[header]
name = "CSpawnGroupMgrGameSystem_UnloadSpawnGroup"
addr = 0xf6ee60

[header.args]
