last_change = 2026-09-09T16:19:01.064532Z
addr = 0xf99300
size = 0x184
name = "CBaseModelEntity_ScriptSetMaterialGroup"

[header]
name = "CBaseModelEntity_ScriptSetMaterialGroup"
addr = 0xf99300

[header.args]
