last_change = 2026-09-09T16:19:01.064446Z
addr = 0xf920a0
size = 0xf
name = "CBaseEntity_ScriptGetSpawnGroupHandle"

[header]
name = "CBaseEntity_ScriptGetSpawnGroupHandle"
addr = 0xf920a0

[header.args]
