last_change = 2026-09-09T16:19:01.064455Z
addr = 0xf92220
size = 0x1c
name = "CBaseEntity_GetLocalAngularVelocity_OBSOLETE"

[header]
name = "CBaseEntity_GetLocalAngularVelocity_OBSOLETE"
addr = 0xf92220

[header.args]
