last_change = 2026-09-09T16:19:01.064512Z
addr = 0xf943c0
size = 0x5
name = "CBaseModelEntity_ScriptSetBodygroupByName"

[header]
name = "CBaseModelEntity_ScriptSetBodygroupByName"
addr = 0xf943c0

[header.args]
