last_change = 2026-09-09T16:19:01.064555Z
addr = 0xfba840
size = 0x2d3a
name = "CBaseModelEntity_GetScriptDescInternal"

[header]
name = "CBaseModelEntity_GetScriptDescInternal"
addr = 0xfba840

[header.args]
