last_change = 2026-09-09T16:19:01.064590Z
addr = 0x1423d80
size = 0x3d
name = "SV_Kill_SmokeGrenade_CommandHandler"

[header]
name = "SV_Kill_SmokeGrenade_CommandHandler"
addr = 0x1423d80

[header.args]
