last_change = 2026-09-09T18:30:05.429694Z
addr = 0x1504f10
size = 0xaf
name = "CCSPlayerController_GetThinkFunction"
type = "long long"

[header]
name = "CCSPlayerController_GetThinkFunction"
addr = 0x1504f10
type = "long long"

[header.args]
