last_change = 2026-09-09T16:19:01.064723Z
addr = 0x160b140
size = 0x5b
name = "CBaseModelEntity_ScriptGetAttachmentAngles"

[header]
name = "CBaseModelEntity_ScriptGetAttachmentAngles"
addr = 0x160b140

[header.args]
