last_change = 2026-09-09T16:19:01.064721Z
addr = 0x160b100
size = 0x39
name = "CBaseModelEntity_ScriptGetAttachmentOrigin"

[header]
name = "CBaseModelEntity_ScriptGetAttachmentOrigin"
addr = 0x160b100

[header.args]
