last_change = 2026-09-09T16:19:01.064750Z
addr = 0x161d640
size = 0x253
name = "CBasePlayerController_SetPlayerName"

[header]
name = "CBasePlayerController_SetPlayerName"
addr = 0x161d640

[header.args]
