last_change = 2026-09-09T16:19:01.064813Z
addr = 0x16d88a0
size = 0x76
name = "CGameEntitySystem_FindEntityByName"

[header]
name = "CGameEntitySystem_FindEntityByName"
addr = 0x16d88a0

[header.args]
