last_change = 2026-09-09T18:30:08.251657Z
addr = 0x16d3e00
size = 0x2dc
name = "CEntitySaveRestoreBlockHandler_RestoreEntity"

[header]
name = "CEntitySaveRestoreBlockHandler_RestoreEntity"
addr = 0x16d3e00

[header.args]
