last_change = 2026-09-09T16:19:01.064836Z
addr = 0x16e47c0
size = 0xd9
name = "CGameSceneNode_UpdateEntityForHierarchyChange"

[header]
name = "CGameSceneNode_UpdateEntityForHierarchyChange"
addr = 0x16e47c0

[header.args]
