last_change = 2026-09-09T16:19:01.065009Z
addr = 0x1809560
size = 0x24
name = "CBaseEntity_Script_ApplyLocalAngularVelocityImpulse"

[header]
name = "CBaseEntity_Script_ApplyLocalAngularVelocityImpulse"
addr = 0x1809560

[header.args]
