last_change = 2026-09-09T16:19:01.065088Z
addr = 0x18ff320
size = 0x4b
name = "CSource2Server_GameServerSteamAPIDeactivated"

[header]
name = "CSource2Server_GameServerSteamAPIDeactivated"
addr = 0x18ff320

[header.args]
