last_change = 2026-09-09T16:19:01.065142Z
addr = 0x19097f0
size = 0xbf
name = "CSource2Server_ServerConVarChanged"

[header]
name = "CSource2Server_ServerConVarChanged"
addr = 0x19097f0

[header.args]
