last_change = 2026-09-09T16:19:01.065126Z
addr = 0x1902fb0
size = 0xd1
name = "CGameRulesGameSystem_OnGameShutdown"

[header]
name = "CGameRulesGameSystem_OnGameShutdown"
addr = 0x1902fb0

[header.args]
