last_change = 2026-09-09T16:19:01.065284Z
addr = 0x213ed10
size = 0x1
name = "CEntitySystem_OnEntityParentChanged"

[header]
name = "CEntitySystem_OnEntityParentChanged"
addr = 0x213ed10

[header.args]
