last_change = 2026-09-09T16:19:35.718012Z
addr = 0x21649a0
size = 0x4d2
name = "CEntityIOOutput_FireOutputInternal"

[header]
name = "CEntityIOOutput_FireOutputInternal"
addr = 0x21649a0

[header.args]
